### ISSUE TITLE
好像不符合题库不变的条件

### ISSUE THREAD

**Issue by Yun-HuBuXi** [kmoonn/Weiban-Tool#3]
我去查了下题库，截至今天，不满足每次重做题库不变的原则了QAQ
len(set(questions_1+questions_2))的结果是75，ORZ

**Comment by kmoonn** [comment]
请问你是研究生吗？因为作者是本科生，该程序目前只在本科生情况下测试通过。

**Comment by Yun-HuBuXi** [comment]
> 请问你是研究生吗？因为作者是本科生，该程序目前只在本科生情况下测试通过。

本科生，不知道为啥哈哈哈哈哈哈哈，我一直只通过25个的答案检测，今天刚做的，可能是改策略了吧

**Comment by kmoonn** [comment]
检查是否正确设置userExamId此参数？如果按照正确执行流程还不满足50/50的情况，那可能是改策略了。我昨天用过1次没出现问题。

**Comment by Yun-HuBuXi** [comment]
都设置正确了，我还复查了一遍（

**Comment by kmoonn** [comment]
主页https://github.com/kmoonn加一下我QQ吧，我看看

**Comment by kmoonn** [comment]
# 问题说明
题库不变机制约束条件：连续两次作答间隔时间不能过长，否则不满足题库不变情况。
